# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test -B

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: hospital-care-jar
        path: target/*.jar

    - name: Create Release (on master push)
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}-${{ github.run_number }}
        release_name: Hospital Care v${{ steps.get_version.outputs.VERSION }}-build${{ github.run_number }}
        body: |
          ## Hospital Care Application Release

          ### Features
          - Patient registration and management
          - JSON export functionality sorted by age (oldest first)
          - CLI application for hospital patient management

          ### Usage
          Download the JAR file and run:
          ```bash
          java -jar hospital-care-${{ steps.get_version.outputs.VERSION }}.jar
          ```

          ### Build Information
          - Version: ${{ steps.get_version.outputs.VERSION }}
          - Build: ${{ github.run_number }}
          - Commit: ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (on master push)
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/hospital-care-${{ steps.get_version.outputs.VERSION }}.jar
        asset_name: hospital-care-${{ steps.get_version.outputs.VERSION }}.jar
        asset_content_type: application/java-archive
